nav:
  Home: /
  Projects: /Projects/
  About: /About/
#   Blog: /archives/
  

projects_url: http://github.com/ericmguzmanc

customize:
    gravatar:
        email:
    logo:
        enabled: true
        width: 50
        height: 50
        url: /images/mainpic2.jpg
        gravatar: false
    favicon:
      # eg. generate with http://realfavicongenerator.net/
      desktop:
        url: /images/mainpic2.jpg
        gravatar: false
      android:
        url: /images/mainpic2.jpg
        gravator: false
      apple:
        url: /images/mainpic2.jpg
        gravator: false
    social_links:
        github: https://github.com/ericmguzmanc
        twitter: https://twitter.com/imericguzman
        linkedin: https://www.linkedin.com/in/imericguzman/ 
    show_all_posts: false
    post_count: 5
    highlight: monokai

# RSS
rss: false

# Plugins
plugins:
    disqus_shortname: # Disqus Comments Shortname
    google_analytics: UA-86660611-1 # enter the tracking ID for your Google Analytics

# Miscellaneous
miscellaneous:
    open_graph: # see http://ogp.me
        fb_app_id:
        fb_admins:
        twitter_id:
        google_plus:
